version: "2"
services:
  peons:
    image: friendlyngeeks/peons-rpi:latest
    container_name: peons
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/usr/src/server
    env_file:
      - ./.env.production.local
    privileged: true