version: "2"
services:
  peons-app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./server:/app/server
      - ./build:/app/build
    env_file:
      - ./.env.production.local