version: "2"
services:
  peons:
    image: friendlyngeeks/peons-rpi:latest
    container_name: peons
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/usr/src/app
    ports:
      - "7000:7000"
    env_file:
      - ./.env.production.local
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    # command: bundle exec thin -d -p 80
    # network_mode: host