version: "2"
services:
  peons:
    # image: friendlyngeeks/peons-rpi:latest
    container_name: peons
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./.env.production.local
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    network_mode: host # console shows device ip HOST