version: "2"
services:
  peons:
    image: friendlyngeeks/peons-rpi:latest
    container_name: peons
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server:/usr/src/server
    env_file:
      - ./.env.production.local