version: "2"
services:
  peons:
    image: friendlyngeeks/peons-rpi:latest
    container_name: peons
    build: .
    ports:
      - "80:80"
    volumes:
      - ./server:/app
    env_file:
      - ../.env.production.local